#Hugo configuration
title = "qweasder3"
baseURL = "https:\/\/asdsa.scv.asd"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758166"
subfolder = ""
